image: node

before_script:
  - npm install --force # Live dangerously

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

pages:
  script:
    - npm run build
    - mv out/* public
  artifacts:
    paths:
      - public
  only:
    - main
